%{
	@file: PD_2025_08_24_a.m
	@brief: Visualize the posterior shadow of data 2025-04-13-b and perform basic analysis.
	@date: [created: 2025-08-24, updated: 2025-08-26]
	@author: madpang
%}

% --- Workspace ---
% @note: Assuming directory structure -- `<workspace-name>/src/<this-script>.m`
ws = fileparts(fileparts(mfilename('fullpath')));
wsPath = genpath(ws);
addpath(wsPath);
inputDir = fullfile(ws, 'data', '2025-04-13-b');
if ~isfolder(inputDir)
	error('Input directory does not exist: %s', inputDir);
end

gridNum = 512;
gridSz = 232./gridNum; % [mm]
gridPos = RegularGrid( ...
	gridSz .* [1, 1], ...
	gridNum .* [1, 1], ...
	[0, 0] ...
);

% --- @todo ---

rxApSz = 610;

ii = 161;

fhIdx = fopen( ...
	fullfile( ...
		inputDir, ...
		['roiIdx', '-', num2str(ii, '%03d'), '.bin'] ...
	), ...
	'r' ...
);

roiIdx = logical(fread(fhIdx, inf, 'logical'));

fclose(fhIdx);

fhRcv = fopen( ...
	fullfile( ...
		inputDir, ...
		['rcvLvl', '-', num2str(ii, '%03d'), '.bin'] ...
	), ...
	'r' ...
);

rcvLvl = reshape(fread(fhRcv, inf, 'single'), [], rxApSz);
fclose(fhRcv);

summedSigMap = NaN(gridNum, gridNum);
summedSigMap(roiIdx) = 20 .* log10(sum(10.^(rcvLvl ./10), 2) ./ 0.218);

unit_sz = 64;
hF1 = createFigure([1, 1], [8, 9], unit_sz);
% --- main content
hA1 = axes( ...
	hF1, ...
	'NextPlot', 'replace', ...
	'Units', 'pixels', ...
	'Position', [2, 1, 8, 8] .* unit_sz, ...
	'FontName', 'Times', ...
	'FontWeight', 'normal', ...	
	'FontSize', 14, ...
	'Colormap', parula(256), ...
	'DataAspectRatioMode', 'auto', ...
	'PlotBoxAspectRatioMode', 'auto', ...
	'XLimMode', 'auto', 'YLimMode', 'auto', 'ZLimMode',  'auto', ...
	'XLimitMethod', 'tight', 'YLimitMethod', 'tight', 'ZLimitMethod', 'tight', ...
	'TickDir', 'none' ...
);
imagesc( ...
	hA1, ...
	'XData', gridPos([1, end], 1), ...
	'YData', gridPos([1, end], 2), ...
	'CData', summedSigMap, ...
	[-120, 0] ... % clims
);
xlim(hA1, 'auto');
ylim(hA1, 'auto');
xlabel( ...
	hA1, ...
	'X-axis range [mm]', ...
	'FontSize', 14 ...
);
ylabel( ...
	hA1, ...
	'Y-axis range [mm]', ...
	'FontSize', 14 ...
);
title( ...
	hA1, ...
	'Summed signal level map across RX aperture', ...
	'FontWeight', 'bold', ...
	'Interpreter', 'none', ...
	'FontSize', 16 ...
);
% --- manual colorbar
hCB1 = axes( ...
	hF1, ...
	'Units', 'pixels', ...
	'Position', [10.5, 1, 0.25, 8] .* unit_sz, ...
	'FontName', 'Times', ...
	'FontWeight', 'normal', ...	
	'FontSize', 12, ...
	'Colormap', parula(256), ...
	'DataAspectRatioMode', 'auto', ...
	'PlotBoxAspectRatioMode', 'auto', ...
	'XLimMode', 'auto', 'YLimMode', 'auto', 'ZLimMode',  'auto', ...
	'XLimitMethod', 'tight', 'YLimitMethod', 'tight', 'ZLimitMethod', 'tight', ...
	'TickDir', 'none', ...
	'XTick', [], ...
	'YAxisLocation', 'right' ...
);
image( ...
	hCB1, ...
	'XData', [0, 1], ...
	'YData', [-120, 0], ...
	'CData', transpose(uint8(0 : 1 : 255)) ...
);
ylabel( ...
	hCB1, ...
	'Normalized Amplitude [dB]', ...
	'FontSize', 12 ...
);

% --- Clean up ---
rmpath(wsPath);
