%{
	@file: PD_2025_08_24_a.m
	@brief: Visualize the posterior shadow of data 2025-04-13-b and perform basic analysis.
	@details:
	- This script generates an animation of the summed signal level for each TX to grasp an intuitive understanding of the posterior shadowing effect.

	@author: madpang
	@date: [created: 2025-08-24, updated: 2025-08-27]
%}

% --- Workspace ---
% @note: Assuming directory structure -- `<workspace-name>/src/<this-script>.m`
ws = fileparts(fileparts(mfilename('fullpath')));
wsPath = genpath(ws);
addpath(wsPath);
inputDir = fullfile(ws, 'data', '2025-04-13-b');
if ~isfolder(inputDir)
	error('Input directory does not exist: %s', inputDir);
end
outputDir = fullfile(ws, 'media');
if ~exist(outputDir, 'dir')
	mkdir(outputDir);
end

% --- Parameters configuration ---
% Number of Transmissions
txNum = 256;
% Reception aperture size (in terms of num. of elements)
rxApSz = 610;
% Pixel grid definition
gridNum = 512;
gridSz = 232./gridNum; % [mm]
gridPos = RegularGrid( ...
	gridSz .* [1, 1], ...
	gridNum .* [1, 1], ...
	[0, 0] ...
);

% --- Data processing ---

% ``` Find the maximal signal level for global scaling
% maxSigLvl = -Inf;
% for ii = 1 : txNum
% 	% Read index
% 	fhIdx = fopen( ...
% 		fullfile( ...
% 			inputDir, ...
% 			['roiIdx', '-', num2str(ii, '%03d'), '.bin'] ...
% 		), ...
% 		'r' ...
% 	);
% 	roiIdx = logical(fread(fhIdx, inf, 'logical'));
% 	fclose(fhIdx);
% 	% Read the received signal level
% 	fhRcv = fopen( ...
% 		fullfile( ...
% 			inputDir, ...
% 			['rcvLvl', '-', num2str(ii, '%03d'), '.bin'] ...
% 		), ...
% 		'r' ...
% 	);
% 	rcvLvl = reshape(fread(fhRcv, inf, 'single'), [], rxApSz);
% 	fclose(fhRcv);

% 	summedSigPerTx = sum(10.^(rcvLvl ./10), 2);
% 	maxSigLvl = max(maxSigLvl, max(summedSigPerTx));
% end
% ```
maxSigLvl = 0.218; % result from the above code block

% --- Animation generation ---
videoObject = VideoWriter( ...
	fullfile( ...
		outputDir, ...
		'data-2025-04-13-b.avi' ...
	) ... % defaults to Motion JPEG AVI profile
);
open(videoObject);
for ii = 1 : txNum
	% Read index
	fhIdx = fopen( ...
		fullfile( ...
			inputDir, ...
			['roiIdx', '-', num2str(ii, '%03d'), '.bin'] ...
		), ...
		'r' ...
	);
	roiIdx = logical(fread(fhIdx, inf, 'logical'));
	fclose(fhIdx);
	% Read the received signal level
	fhRcv = fopen( ...
		fullfile( ...
			inputDir, ...
			['rcvLvl', '-', num2str(ii, '%03d'), '.bin'] ...
		), ...
		'r' ...
	);
	rcvLvl = reshape(fread(fhRcv, inf, 'single'), [], rxApSz);
	fclose(fhRcv);

	% Figure creation
	summedSigMap = NaN(gridNum, gridNum);
	summedSigMap(roiIdx) = 20 .* log10(sum(10.^(rcvLvl ./10), 2) ./ maxSigLvl);

	hF = showMap( ...
		summedSigMap, ...
		[-120, 0], ... % -120 dB and below would be map to lowest color in the map
		[transpose(gridPos([1, end], 1)), transpose(gridPos([1, end], 2))], ...
		sprintf('Summed signal level map for TX #%03d', ii) ...
	);

	% Write frame to video
	writeVideo(videoObject, getframe(hF));
	close(hF);

	% Progress bar
	per = ii / txNum;
	str_p1 = sprintf('%5.1f%', per * 100);
	str_p2 = [ ...
		'[', ...
		repmat('>', 1, floor(per * 50)), ...
		repmat(' ', 1, 50 - floor(per * 50)) ...
		']' ...
	];
	fprintf([str_p1, '%%', ' ', str_p2]);
	fprintf('\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b');
end
fprintf('\n');
close(videoObject);

% --- Clean up ---
rmpath(wsPath);

% === Local function{s}
%{
	@brief: Visualize the summed signal level map.

	@param[out]:
	- hF: figure handle
	@param[in]:
	- summedSigMap: matrix data to be visualized
	- dataRange: range of data values for visualization, [min, max]
	- xyRange: [xRange, yRange] for the image display
	- optTitle: optional title for the figure

	@note:
	- This function depends on createFigure.m
%}
function hF = showMap(summedSigMap, dataRange, xyRange, optTitle)
	% --- Figure parameters
	sizeUnit = 64;
	marginSize = [2, 1];
	axesSize = [8, 8, 0.25, 8]; % each two set an axes (width, height)
	kerfSize = 0.5;
	realAssetSize = [axesSize(1) + axesSize(3) + kerfSize, max(axesSize(2), axesSize(4))]; % [width, height]

	% --- Data parameters
	colorMap = parula(256);
	if nargin < 4
		optTitle = 'Summed signal level map across RX aperture';
	end
	figTitle = optTitle;
	mainFontSize = 14;
	titleFontSize = mainFontSize + 2;
	colorBarFontSize = mainFontSize - 2;

	% --- Visualization
	% Create figure
	hF = createFigure(sizeUnit, realAssetSize, marginSize);

	% Create axes
	hA = axes( ...
		hF, ...
		'NextPlot', 'replace', ...
		'Units', 'pixels', ...
		'Position', [marginSize(1), marginSize(2), axesSize(1), axesSize(2)] .* sizeUnit, ...
		'FontName', 'Times', ...
		'FontWeight', 'normal', ...
		'FontSize', mainFontSize, ...
		'Colormap', colorMap, ...
		'DataAspectRatioMode', 'auto', ...
		'PlotBoxAspectRatioMode', 'auto', ...
		'XLimMode', 'auto', 'YLimMode', 'auto', 'ZLimMode',  'auto', ...
		'XLimitMethod', 'tight', 'YLimitMethod', 'tight', 'ZLimitMethod', 'tight', ...
		'TickDir', 'none' ...
	);
	% Display the image
	imagesc( ...
		hA, ...
		'XData', xyRange(1:2), ...
		'YData', xyRange(3:4), ...
		'CData', summedSigMap, ...
		dataRange ... % clims
	);
	xlim(hA, 'auto');
	ylim(hA, 'auto');
	xlabel( ...
		hA, ...
		'X-axis range [mm]', ...
		'FontSize', mainFontSize ...
	);
	ylabel( ...
		hA, ...
		'Y-axis range [mm]', ...
		'FontSize', mainFontSize ...
	);
	title( ...
		hA, ...
		figTitle, ...
		'FontWeight', 'bold', ...
		'Interpreter', 'none', ...
		'FontSize', titleFontSize ...
	);

	% Create colorbar (manually)
	hCB = axes( ...
		hF, ...
		'Units', 'pixels', ...
		'Position', [marginSize(1) + axesSize(1) + kerfSize, marginSize(2), axesSize(3), axesSize(4)] .* sizeUnit, ...
		'FontName', 'Times', ...
		'FontWeight', 'normal', ...	
		'FontSize', colorBarFontSize, ...
		'Colormap', colorMap, ...
		'DataAspectRatioMode', 'auto', ...
		'PlotBoxAspectRatioMode', 'auto', ...
		'XLimMode', 'auto', 'YLimMode', 'auto', 'ZLimMode',  'auto', ...
		'XLimitMethod', 'tight', 'YLimitMethod', 'tight', 'ZLimitMethod', 'tight', ...
		'TickDir', 'none', ...
		'XTick', [], ...
		'YAxisLocation', 'right' ...
	);
	image( ...
		hCB, ...
		'XData', [0, 1], ...
		'YData', dataRange, ...
		'CData', transpose(uint8(0 : 1 : 255)) ...
	);
	ylabel( ...
		hCB, ...
		'Normalized Amplitude [dB]', ...
		'FontSize', colorBarFontSize ...
	);
end
